-- ============================================================================
-- TAAREEF · MEASUREMENT LAYER
-- Repo path: supabase/migrations/20260812_measurement_layer.sql
-- Run in: Supabase SQL Editor (project tcuyfrcmjrtczneklhmx)
-- Spec:   KB-MEASUREMENT_SPEC.md
--
-- ADDITIVE ONLY. No existing table is altered destructively. No existing
-- behaviour changes. No UI changes. Safe to run on production.
--
-- Run PART 1 → 5 IN ORDER. Each part is independently re-runnable except
-- where noted. Verification queries are at the bottom.
-- ============================================================================


-- ============================================================================
-- PART 1 — Enum types
-- ============================================================================

CREATE TYPE event_kind AS ENUM (
  'app_opened','category_viewed','card_opened',
  'save_started','save_completed','save_abandoned',
  'status_changed','search_performed','search_result_opened',
  'enrichment_shown','enrichment_resolved','source_browsed'
);

CREATE TYPE event_surface AS ENUM (
  'dashboard','category_list','card_detail','capture_sheet',
  'save_peek','search','source_list','taareef_folder',
  'onboarding','profile','other'
);

CREATE TYPE day_part AS ENUM ('morning','afternoon','evening','night');

CREATE TYPE enrichment_band AS ENUM ('sure','fairly_sure','not_sure');

-- THREE outcomes, not two. "No correction" is NOT the same as "correct" —
-- the user may not have noticed. Collapsing 'untouched' into 'accepted'
-- would flatter the confidence bands, which is the exact failure this measures.
CREATE TYPE enrichment_outcome AS ENUM ('accepted','corrected','untouched');

CREATE TYPE found_via AS ENUM (
  'search','category_browse','source_list','taareef_folder',
  'save_peek','direct_link','unknown'
);

-- What made the user finally act. Asked once, skippable.
-- 'stumbled_here' is the only direct evidence the vault CAUSED something.
CREATE TYPE completion_trigger AS ENUM (
  'reminded','was_nearby','planned','stumbled_here','skipped'
);


-- ============================================================================
-- PART 2 — events (partitioned)
-- ============================================================================
-- Partitioned by local_date so retention is DROP PARTITION — instant, and it
-- actually returns disk to the OS. Plain DELETE leaves dead tuples and needs
-- VACUUM FULL, which takes an exclusive lock. This cannot be retrofitted
-- without downtime, which is why it is here on day one.

CREATE TABLE events (
  id              bigint GENERATED BY DEFAULT AS IDENTITY,
  user_id         uuid REFERENCES auth.users(id) ON DELETE SET NULL,
  session_id      uuid          NOT NULL,
  kind            event_kind    NOT NULL,
  surface         event_surface NOT NULL DEFAULT 'other',
  occurred_at     timestamptz   NOT NULL,
  recorded_at     timestamptz   NOT NULL DEFAULT now(),
  local_date      date          NOT NULL,
  part_of_day     day_part      NOT NULL,
  category        category      NULL,
  card_id         uuid          NULL,
  correlation_id  uuid          NULL,
  payload         jsonb         NOT NULL DEFAULT '{}'::jsonb,
  PRIMARY KEY (id, local_date)
) PARTITION BY RANGE (local_date);

COMMENT ON TABLE events IS
  'Activity log. NEVER contains user content (titles, notes, locations). card_id joins to recommendations. See KB-MEASUREMENT_SPEC.md.';
COMMENT ON COLUMN events.user_id IS
  'ON DELETE SET NULL, not CASCADE — anonymous-user cleanup must delete the account and KEEP the history.';
COMMENT ON COLUMN events.category IS
  'Category AS IT WAS at event time. Does not follow later recategorisation. Intentional — history does not rewrite itself.';
COMMENT ON COLUMN events.occurred_at IS 'Client clock. Untrusted. Needed for offline queue replay.';
COMMENT ON COLUMN events.recorded_at IS 'Server clock. Authoritative.';
COMMENT ON COLUMN events.local_date IS 'User local date. Rollups group on THIS, not UTC — IST is +5:30, so every evening would otherwise land on the next day.';

-- ONE index to start. Measured index:data ratio on this database is ~12:1,
-- so every additional index is a permanent tax on every write.
CREATE INDEX events_user_date_idx ON events (user_id, local_date DESC);

-- Safety net: a missing monthly partition would make INSERT fail, which would
-- break a user action. Rows landing here are never auto-dropped.
CREATE TABLE events_default PARTITION OF events DEFAULT;

-- Monthly partitions, 12 months ahead.
DO $$
DECLARE m date := date_trunc('month', current_date)::date;
BEGIN
  FOR i IN 0..11 LOOP
    EXECUTE format(
      'CREATE TABLE IF NOT EXISTS events_%s PARTITION OF events FOR VALUES FROM (%L) TO (%L)',
      to_char(m + (i || ' months')::interval, 'YYYY_MM'),
      (m + (i || ' months')::interval)::date,
      (m + ((i+1) || ' months')::interval)::date
    );
  END LOOP;
END $$;

ALTER TABLE events ENABLE ROW LEVEL SECURITY;

CREATE POLICY events_insert_own ON events
  FOR INSERT TO authenticated WITH CHECK (user_id = auth.uid());
CREATE POLICY events_select_own ON events
  FOR SELECT TO authenticated USING (user_id = auth.uid());


-- ============================================================================
-- PART 3 — search_log
-- ============================================================================
-- NOT part of events, and never rolled up. This is the ground-truth evaluation
-- set for building retrieval later. Its value is the individual query→open
-- pairs; a rollup would destroy exactly what makes it useful.
-- Zero-result rows are the highest-value product signal in the whole system.

CREATE TABLE search_log (
  id                bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id           uuid REFERENCES auth.users(id) ON DELETE SET NULL,
  session_id        uuid        NOT NULL,
  query_text        text        NOT NULL,
  result_count      integer     NOT NULL,
  opened_card_id    uuid        NULL,
  opened_rank       integer     NULL,
  was_reformulation boolean     NOT NULL DEFAULT false,
  latency_ms        integer     NULL,
  local_date        date        NOT NULL,
  created_at        timestamptz NOT NULL DEFAULT now()
);

COMMENT ON TABLE search_log IS
  'Retrieval ground truth. Retained forever, never rolled up, exempt from the 90-day window.';

CREATE INDEX search_log_user_date_idx ON search_log (user_id, local_date DESC);

ALTER TABLE search_log ENABLE ROW LEVEL SECURITY;
CREATE POLICY search_log_insert_own ON search_log
  FOR INSERT TO authenticated WITH CHECK (user_id = auth.uid());
CREATE POLICY search_log_select_own ON search_log
  FOR SELECT TO authenticated USING (user_id = auth.uid());
CREATE POLICY search_log_update_own ON search_log
  FOR UPDATE TO authenticated USING (user_id = auth.uid());


-- ============================================================================
-- PART 4 — Rollup + snapshot tables
-- ============================================================================
-- GRAIN IS THE WHOLE DECISION. Anything in the grain survives forever;
-- anything not in it dies with the raw events. user_id + local_date never
-- leave the grain — that is what keeps every future cohort definition askable.

CREATE TABLE rollup_daily (
  user_id           uuid     NOT NULL,
  local_date        date     NOT NULL,
  category          category NULL,
  part_of_day       day_part NOT NULL,
  app_opens         integer  NOT NULL DEFAULT 0,
  category_views    integer  NOT NULL DEFAULT 0,
  cards_opened      integer  NOT NULL DEFAULT 0,
  saves_started     integer  NOT NULL DEFAULT 0,
  saves_completed   integer  NOT NULL DEFAULT 0,
  saves_abandoned   integer  NOT NULL DEFAULT 0,
  completions       integer  NOT NULL DEFAULT 0,
  dismissals        integer  NOT NULL DEFAULT 0,
  searches          integer  NOT NULL DEFAULT 0,
  search_opens      integer  NOT NULL DEFAULT 0,
  source_browses    integer  NOT NULL DEFAULT 0,
  PRIMARY KEY (user_id, local_date, category, part_of_day)
);

COMMENT ON TABLE rollup_daily IS
  'Behavioural rollup. Cohorts are defined AT QUERY TIME by joining user_id to first-save date — never pre-computed.';

-- Aimed squarely at the live problem: cards opened repeatedly, never completed.
CREATE TABLE rollup_card_monthly (
  card_id      uuid    NOT NULL,
  user_id      uuid    NULL,
  month        date    NOT NULL,
  opens        integer NOT NULL DEFAULT 0,
  completed    boolean NOT NULL DEFAULT false,
  PRIMARY KEY (card_id, month)
);

CREATE TABLE rollup_enrichment (
  local_date date            NOT NULL,
  category   category        NULL,
  band       enrichment_band NOT NULL,
  shown      integer NOT NULL DEFAULT 0,
  accepted   integer NOT NULL DEFAULT 0,
  corrected  integer NOT NULL DEFAULT 0,
  untouched  integer NOT NULL DEFAULT 0,
  PRIMARY KEY (local_date, category, band)
);

COMMENT ON TABLE rollup_enrichment IS
  'Calibration. Answers: of everything we called fairly_sure, what share was actually right?';

-- An event log is structurally BLIND to inaction. 27 untouched saves generate
-- zero events. Only a periodic photograph shows a backlog going stale.
CREATE TABLE snapshot_weekly (
  user_id                          uuid    NOT NULL,
  week_start                       date    NOT NULL,
  total_saved                      integer NOT NULL,
  never_reopened                   integer NOT NULL,
  oldest_untouched_days            integer NULL,
  completed_ever                   integer NOT NULL,
  completed_this_week              integer NOT NULL,
  categories_with_zero_completions integer NOT NULL,
  saves_added_this_week            integer NOT NULL,
  captured_at                      timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY (user_id, week_start)
);

COMMENT ON COLUMN snapshot_weekly.oldest_untouched_days IS
  'THE headline number. Climbs 1/day if the bottom of the vault is dead. If it ever DROPS, something down there was rescued — find out what caused that.';

ALTER TABLE rollup_daily         ENABLE ROW LEVEL SECURITY;
ALTER TABLE rollup_card_monthly  ENABLE ROW LEVEL SECURITY;
ALTER TABLE rollup_enrichment    ENABLE ROW LEVEL SECURITY;
ALTER TABLE snapshot_weekly      ENABLE ROW LEVEL SECURITY;

CREATE POLICY rollup_daily_select_own ON rollup_daily
  FOR SELECT TO authenticated USING (user_id = auth.uid());
CREATE POLICY rollup_card_select_own ON rollup_card_monthly
  FOR SELECT TO authenticated USING (user_id = auth.uid());
CREATE POLICY snapshot_select_own ON snapshot_weekly
  FOR SELECT TO authenticated USING (user_id = auth.uid());
-- rollup_enrichment has no user_id: service-role only, no policy = no access.


-- ============================================================================
-- PART 5 — Two additive columns on recommendations
-- ============================================================================
-- NOT re-runnable as-is (backfill). Run once.

ALTER TABLE recommendations ADD COLUMN IF NOT EXISTS status_changed_at timestamptz NULL;
ALTER TABLE recommendations ADD COLUMN IF NOT EXISTS last_opened_at    timestamptz NULL;

COMMENT ON COLUMN recommendations.status_changed_at IS
  'When status last changed. The north-star metric reads this. Rows backfilled 2026-08-12 from updated_at are APPROXIMATE — updated_at moves on any edit.';
COMMENT ON COLUMN recommendations.last_opened_at IS
  'Durable. Weekly snapshot needs this to compute never_reopened and oldest_untouched beyond the 90-day event window.';

-- Backfill: approximate, and only for rows that have actually moved.
UPDATE recommendations
   SET status_changed_at = updated_at
 WHERE status <> 'saved'
   AND status_changed_at IS NULL;


-- ============================================================================
-- VERIFICATION — run after the parts above
-- ============================================================================

-- 1. All six tables exist
SELECT tablename FROM pg_tables
 WHERE schemaname = 'public'
   AND tablename IN ('events','search_log','rollup_daily',
                     'rollup_card_monthly','rollup_enrichment','snapshot_weekly')
 ORDER BY tablename;
-- EXPECT: 6 rows.

-- 2. events is partitioned, with 12 monthly partitions + default
SELECT count(*) AS partition_count FROM pg_inherits
 WHERE inhparent = 'events'::regclass;
-- EXPECT: 13.

-- 3. Backfill landed on exactly the 6 non-saved rows
SELECT status, count(*) AS n, count(status_changed_at) AS with_timestamp
  FROM recommendations GROUP BY status ORDER BY n DESC;
-- EXPECT: saved 27 / 0 with_timestamp
--         experienced 3 / 3
--         dismissed 3 / 3
-- BROKEN LOOKS LIKE: any saved row with a timestamp, or a non-saved row without.

-- 4. RLS is on everywhere
SELECT relname, relrowsecurity FROM pg_class
 WHERE relname IN ('events','search_log','rollup_daily',
                   'rollup_card_monthly','rollup_enrichment','snapshot_weekly');
-- EXPECT: all true.

-- 5. Only ONE index on events (plus the PK)
SELECT indexname FROM pg_indexes WHERE tablename = 'events';
-- EXPECT: events_pkey, events_user_date_idx. Nothing else.
